# http://www.appveyor.com/docs/appveyor-yml

# Test against these versions of Node.js.
environment:
  MOCHA_REPORTER: "mocha-appveyor-reporter"
  matrix:
    - nodejs_version: "6"

# Install scripts. (runs after repo cloning)
install:
  - git rev-parse HEAD
  # Get the latest stable version of Node 0.STABLE.latest
  - ps: Install-Product node $env:nodejs_version
  - npm install mocha-appveyor-reporter
  - npm install -g bower
  # Typical npm stuff.
  - npm version
  - npm install
  - bower install

cache:
  - '%APPDATA%\npm-cache'
  - '%APPDATA%\Roaming\bower'


# Post-install test scripts.
test_script:
  # Output useful info for debugging.
  - npm version
  - cmd: node_modules/.bin/ember try:one ember-beta --- "echo 5 && echo 3"
  - cmd: node_modules/.bin/ember try:each

# Don't actually build.
build: off

# Set build version format here instead of in the admin panel.
version: "{build}"
